buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            name = "forge"
            url = "https://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

repositories {
    mavenLocal()
    mavenCentral()

    // JEI
    maven {
        name = "JEI"
        url = "https://dvs1.progwml6.com/files/maven"
    }

    // CoFH / Thermal
    maven {
        name = "CoFH"
        url = "https://maven.covers1624.net"
    }

    // EnderIO
    maven {
        name = "EnderIO"
        url = "https://maven.tterrag.com"
    }

    // Curse Maven (Hwyla)
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
    }

    // Forge
    maven {
        url = "https://files.minecraftforge.net/maven"
    }

    // Thiakil
    maven {
        name = "thiakil"
        url = "https://maven.thiakil.com"
    }
}

version = project.version
group = "zairus.${modid}"
archivesBaseName = "${modid}-${mcversion}"

sourceCompatibility = targetCompatibility = "1.8"

compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    version = "${mcversion}-${forgeversion}"
    runDir = "run"
    mappings = "snapshot_20171003"
}

configurations {
    mods
}

dependencies {
    deobfCompile "com.azanor.baubles:Baubles:1.12-1.5.2"
    deobfCompile "mezz.jei:jei_1.12.2:${jei_version}"

    // Hwyla (FIX)
    deobfCompile "curse.maven:hwyla-253449:2568751"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand(
            'version': project.version,
            'mcversion': project.minecraft.version
        )
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes 'FMLAT': 'ml_at.cfg'
    }
}
